In [1]:
import numpy as np

In [2]:
import scipy.linalg as la

In [16]:
a=np.array([[1,3],[-1,7]])

In [17]:
a

array([[ 1,  3],
       [-1,  7]])

In [7]:
x.ndim

2

In [8]:
x.shape

(2, 2)

In [12]:
x.reshape(4,1)

array([[ 1],
       [-1],
       [ 2],
       [ 3]])

In [23]:
I=np.eye(2,2)

In [18]:
a

array([[ 1,  3],
       [-1,  7]])

In [20]:
b=np.array([[5,2],[1,2]])

In [21]:
b

array([[5, 2],
       [1, 2]])

In [27]:
2*I+3*a-a@b

array([[-3.,  1.],
       [-5., 11.]])

In [28]:
c=np.array([[3,4],[-1,5]])

In [31]:
c

array([[ 3,  4],
       [-1,  5]])

In [32]:
from numpy.linalg import matrix_power as mpow

In [33]:
mpow(c,2)

array([[ 5, 32],
       [-8, 21]])

In [34]:
print(c.T)

[[ 3 -1]
 [ 4  5]]


In [35]:
la.inv(c)

array([[ 0.26315789, -0.21052632],
       [ 0.05263158,  0.15789474]])

In [36]:
la.det(c)

19.0

In [37]:
a=np.array([[2,2],[2,2]])

In [38]:
a

array([[2, 2],
       [2, 2]])

In [39]:
c

array([[ 3,  4],
       [-1,  5]])

In [40]:
np.dot(a,c)

array([[ 4, 18],
       [ 4, 18]])

In [71]:
#for projections
def proj(v,w):
    v=np.array(v)
    w=np.array(w)
    return np.sum(v*w)/np.sum(w*w) *w

In [72]:
x=np.array([3,4]).reshape(2,1)

In [73]:
y=np.array([2,1]).reshape(2,1)

In [74]:
y

array([[2],
       [1]])

In [75]:
x

array([[3],
       [4]])

In [76]:
proj(x,y)

array([[4.],
       [2.]])

In [79]:
x=la.eig(c)

In [88]:
x[1]

array([[0.89442719+0.j        , 0.89442719-0.j        ],
       [0.2236068 +0.38729833j, 0.2236068 -0.38729833j]])

In [82]:
A = np.array([[1,0],[0,-2]])
print(A)

[[ 1  0]
 [ 0 -2]]


In [83]:
results = la.eig(A)

In [85]:
results[0]

array([ 1.+0.j, -2.+0.j])

In [86]:
results[1]

array([[1., 0.],
       [0., 1.]])