In [2]:
my_list=[1,2,3]

In [2]:
import numpy as np

In [4]:
arr=np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.zeros(3)

array([0., 0., 0.])

In [9]:
#Tuples are used to make two dimensional arrays
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [10]:
np.random.rand(5,5)

array([[0.93126786, 0.89971051, 0.78719643, 0.93911762, 0.56808576],
       [0.76649879, 0.80489465, 0.37773851, 0.66050036, 0.45656383],
       [0.08193258, 0.96149792, 0.83541297, 0.53002136, 0.63196155],
       [0.42259906, 0.40645182, 0.87258916, 0.97558972, 0.41615406],
       [0.82847631, 0.25549841, 0.99468861, 0.23850843, 0.73682094]])

In [11]:
np.random.rand(5)

array([0.69671446, 0.85382758, 0.51198576, 0.45666936, 0.56192327])

In [14]:
np.random.randn(2)

array([ 0.83105656, -0.48423998])

In [15]:
arr=np.arange(0,25)

In [16]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [17]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
from numpy.random import randint

In [22]:
randint(0,20)

3

In [6]:
np.random.randint(1,100,10)

array([95, 17,  1, 82, 70, 16, 38, 93, 55, 18])

In [2]:
np.random.randn(4)

array([-0.16399677, -0.28808766,  0.36926126, -1.57668054])

In [23]:
np.random.randint(0,20)

18

In [6]:
arr1=np.arange(0,11)

In [7]:
arr1[0:5]

array([0, 1, 2, 3, 4])

In [8]:
arr1[0:5]=100

In [9]:
arr1

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [10]:
slice_of_arr1=arr1[0:6]

In [11]:
slice_of_arr1

array([100, 100, 100, 100, 100,   5])

In [12]:
slice_of_arr1[:]=99

In [13]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [14]:
arr2_copy=slice_of_arr1.copy()

In [15]:
arr2_copy

array([99, 99, 99, 99, 99, 99])

In [16]:
arr2_copy[:]=10

In [17]:
arr2_copy

array([10, 10, 10, 10, 10, 10])

In [18]:
slice_of_arr1

array([99, 99, 99, 99, 99, 99])

In [19]:
arr=np.arange(0,6)

In [20]:
arr

array([0, 1, 2, 3, 4, 5])

In [23]:
arr_2d=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [24]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
arr_2d[0][0]

1

In [26]:
arr_2d[2,0]

7

In [27]:
arr_2d[1,2]

6

In [28]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [30]:
arr_2d[1:,1:]

array([[5, 6],
       [8, 9]])

In [31]:
bool_arr=arr>5

In [32]:
bool_arr

array([False, False, False, False, False, False])

In [36]:
arr=np.arange(70,79)

In [41]:
arr=arr.reshape((3,3))

In [42]:
bool_arr=arr>74

In [43]:
bool_arr

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [44]:
arr[bool_arr]

array([75, 76, 77, 78])

In [45]:
arr

array([[70, 71, 72],
       [73, 74, 75],
       [76, 77, 78]])

In [46]:
arr[arr<76]

array([70, 71, 72, 73, 74, 75])

In [47]:
arr_2d1=np.arange(50)

In [52]:
arr_2d1=arr_2d1.reshape(5,10)

In [54]:
arr_2d1[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [55]:
arr*arr

array([[4900, 5041, 5184],
       [5329, 5476, 5625],
       [5776, 5929, 6084]])

In [56]:
arr+arr

array([[140, 142, 144],
       [146, 148, 150],
       [152, 154, 156]])

In [57]:
arr/arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [58]:
arr-arr


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [59]:
arr*100

array([[7000, 7100, 7200],
       [7300, 7400, 7500],
       [7600, 7700, 7800]])

In [60]:
arr+100

array([[170, 171, 172],
       [173, 174, 175],
       [176, 177, 178]])

In [61]:
arr**0.5

array([[8.36660027, 8.42614977, 8.48528137],
       [8.54400375, 8.60232527, 8.66025404],
       [8.71779789, 8.77496439, 8.83176087]])

In [63]:
np.log(arr)

array([[4.24849524, 4.26267988, 4.27666612],
       [4.29045944, 4.30406509, 4.31748811],
       [4.33073334, 4.34380542, 4.35670883]])

In [64]:
np.sin(arr)

array([[ 0.77389068,  0.95105465,  0.25382336],
       [-0.67677196, -0.98514626, -0.38778164],
       [ 0.56610764,  0.99952016,  0.51397846]])

In [68]:
np.cos(arr)

array([[ 0.6333192 , -0.30902273, -0.96725059],
       [-0.73619272,  0.17171734,  0.92175127],
       [ 0.82433133, -0.03097503, -0.85780309]])

In [69]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
arr=np.arange(0,20)

In [9]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
arr[:5]

array([0, 1, 2, 3, 4])